<a href="https://colab.research.google.com/github/skdding3/Code-Practice/blob/main/TensorFlow/Eager_Execution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Eager Execution (즉시실행)

In [ ]:
import tensorflow as tf
print(tf.executing_eagerly())

True


In [ ]:
sun = 1
ki = 2
sunki = tf.math.add(sun, ki)
print(sunki)

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
sunki.numpy()

3

In [ ]:
a = tf.constant([[1,2],
                [3,4]])

print (a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


NumPy tf.Tensor.numpy method ndarray

In [ ]:
b = tf.add(a,1)

b       #Broadcasting

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
print (b) #print

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [ ]:
print (a * b) #연산자 오버로딩

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)
