# Vector

In [1]:
# 라이브러리 불러오기
import tensorflow as tf
import numpy as np

# 1차원 배열 정의 
py_list = [10., 20., 30., 40.] # 파이썬 리스트 활용
num_arr = np.array([10., 10., 10., 10.]) # 넘파이 배열 활용

# 텐서 변환
vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(num_arr, dtype=tf.float32)

# 텐처 출력
print("vec1:", vec1)
print("vec2:", vec2)

vec1: tf.Tensor([10. 20. 30. 40.], shape=(4,), dtype=float32)
vec2: tf.Tensor([10. 10. 10. 10.], shape=(4,), dtype=float32)


In [2]:
# 랭크 확인
print(tf.rank(vec1))
print(tf.rank(vec2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [3]:
# 덧셈 함수
add1 = tf.math.add(vec1, vec2)
print("result:", add1)
print("rank:", tf.rank(add1))

result: tf.Tensor([20. 30. 40. 50.], shape=(4,), dtype=float32)
rank: tf.Tensor(1, shape=(), dtype=int32)


In [4]:
# 덧셈 연산자
add2 = vec1 + vec2
print("result:", add2)
print("rank:", tf.rank(add2))

result: tf.Tensor([20. 30. 40. 50.], shape=(4,), dtype=float32)
rank: tf.Tensor(1, shape=(), dtype=int32)


In [5]:
# tf.math 모듈 함수
print(tf.math.subtract(vec1, vec2))
print(tf.math.multiply(vec1, vec2))
print(tf.math.divide(vec1, vec2))
print(tf.math.mod(vec1, vec2))
print(tf.math.floordiv(vec1, vec2))

tf.Tensor([ 0. 10. 20. 30.], shape=(4,), dtype=float32)
tf.Tensor([100. 200. 300. 400.], shape=(4,), dtype=float32)
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor([0. 0. 0. 0.], shape=(4,), dtype=float32)
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [6]:
# 파이썬 연산자
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)
print(vec1 % vec2)
print(vec1 // vec2)

tf.Tensor([ 0. 10. 20. 30.], shape=(4,), dtype=float32)
tf.Tensor([100. 200. 300. 400.], shape=(4,), dtype=float32)
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor([0. 0. 0. 0.], shape=(4,), dtype=float32)
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [7]:
# 합계 구하기
print ( tf.reduce_sum(vec1) )
print ( tf.reduce_sum(vec2) )

tf.Tensor(100.0, shape=(), dtype=float32)
tf.Tensor(40.0, shape=(), dtype=float32)


In [8]:
# 거듭제곱
print( tf.math.square(vec1) )

tf.Tensor([ 100.  400.  900. 1600.], shape=(4,), dtype=float32)


In [9]:
# 거듭제곱 (파이썬 연산자)
print( vec1**2 )

tf.Tensor([ 100.  400.  900. 1600.], shape=(4,), dtype=float32)


In [10]:
# 제곱근
print( tf.math.sqrt(vec2) )

tf.Tensor([3.1622777 3.1622777 3.1622777 3.1622777], shape=(4,), dtype=float32)


In [11]:
# 제곱근 (파이썬 연산자)
print( vec2**0.5 )

tf.Tensor([3.1622777 3.1622777 3.1622777 3.1622777], shape=(4,), dtype=float32)


In [12]:
# 브로드캐스팅 연산 
print (vec1 + 1)

tf.Tensor([11. 21. 31. 41.], shape=(4,), dtype=float32)
